name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

    jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to DockerHub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: philiplinden/opencv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }} # don't use cache for scheduled builds
        registry: docker.com
        tags: latest, $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
  publish-github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: philiplinden/opencv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        registry: docker.pkg.github.com
        tags: latest, $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        