name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

env:
  VERSION: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

jobs:
  build:
    runs-on: ubuntu-latest
    run: 
  update-readme:
    - name: Update Docker Hub Readme
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: philiplinden/opencv
  publish-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to DockerHub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        registry: docker.com
        tags: latest, $VERSION
  publish-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        registry: docker.pkg.github.com
        tags: latest, $VERSION
        